#!/usr/bin/env php
<?php

use Amplify\MediaExporter\Commands\UploadFileToS3Command;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;
use Amplify\MediaExporter\Commands\IndexFileCommand;

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

// Bootstrap application and handle the command...
$console = new Application();

//Register console commands
$console->add(new IndexFileCommand);
$console->add(new UploadFileToS3Command);

exit($console->run());