#!/usr/bin/env php
<?php

use Amplify\MediaExporter\Commands\UploadFileToS3Command;
use Symfony\Component\Console\Application;
use Amplify\MediaExporter\Commands\IndexFileCommand;

define('EXPORTER_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap application and handle the command...
$console = new Application();

//Register console commands
$console->add(new IndexFileCommand);
$console->add(new UploadFileToS3Command);

$status = $console->run();

exit($status);